spring.application.name=student-management-system

server.port=${PORT:8081}

# Database
spring.datasource.url=${DB_URL:jdbc:mysql://student-management-db-rohinsainomula-7bf7.k.aivencloud.com:28768/student_management?sslMode=REQUIRED}
spring.datasource.username=${DB_USERNAME:avnadmin}
spring.datasource.password=${DB_PASSWORD:}

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.open-in-view=false

# JWT
jwt.secret=${JWT_SECRET:}
jwt.expiration=${JWT_EXPIRATION:86400000}

# CORS
app.frontend-url=${FRONTEND_URL:http://localhost:5173}